/**
 * The one rule lives here, in `assertOwner`:
 *   everyone can read every send; you can only write your own.
 *
 * Identity is honour-system — you pick your name from a list and it goes in a
 * cookie. That's deliberate for a group of ten who know each other. It is NOT
 * authentication: anyone who can reach the app can claim to be anyone. What the
 * cookie does buy is that the *client* can't quietly post as someone else — the
 * server never trusts a member_id from the request body.
 */

const COOKIE = "climb_member";

// `Env` and the runtime types come from worker-configuration.d.ts, generated by
// `npm run types` from wrangler.jsonc. Re-run it after changing any binding.

type Json = Record<string, unknown> | unknown[];

const json = (body: Json, init: ResponseInit = {}) =>
  new Response(JSON.stringify(body), {
    ...init,
    headers: { "content-type": "application/json", ...(init.headers ?? {}) },
  });

class HttpError extends Error {
  constructor(readonly status: number, message: string) {
    super(message);
  }
}

function readMemberId(req: Request): number | null {
  const raw = req.headers.get("cookie") ?? "";
  const hit = raw.split(";").map((c) => c.trim()).find((c) => c.startsWith(`${COOKIE}=`));
  if (!hit) return null;
  return positiveInt(hit.slice(COOKIE.length + 1));
}

async function memberExists(env: Env, id: number): Promise<boolean> {
  const row = await env.DB.prepare("SELECT 1 FROM members WHERE id = ?").bind(id).first();
  return row !== null;
}

/**
 * Write paths need a member that actually exists: the cookie lasts a year, so it
 * can outlive the row it names (and nothing stops someone typing a number into
 * it). One indexed lookup turns what would otherwise be a foreign-key 500 into
 * a 401, which sends the client back to the name picker.
 */
async function requireMe(req: Request, env: Env): Promise<number> {
  const id = readMemberId(req);
  if (id === null || !(await memberExists(env, id))) {
    throw new HttpError(401, "Pick who you are first.");
  }
  return id;
}

/** The rule. */
async function assertOwner(env: Env, sendId: number, meId: number) {
  const row = await env.DB.prepare("SELECT member_id FROM sends WHERE id = ?")
    .bind(sendId)
    .first<{ member_id: number }>();
  if (!row) throw new HttpError(404, "No such send.");
  if (row.member_id !== meId) {
    throw new HttpError(403, "That's someone else's send — you can only change your own.");
  }
}

async function body(req: Request): Promise<Record<string, unknown>> {
  try {
    const parsed = await req.json();
    if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
      return parsed as Record<string, unknown>;
    }
  } catch {
    /* fall through */
  }
  throw new HttpError(400, "Expected a JSON object.");
}

/**
 * Positive integer, or null. Deliberately narrow: only a real integer or a
 * string of plain digits. `Number()` on its own would happily turn `true`,
 * `[3]`, `" 3 "` and `"3.0"` into an id.
 */
function positiveInt(v: unknown): number | null {
  if (typeof v === "number") return Number.isInteger(v) && v > 0 ? v : null;
  if (typeof v === "string" && /^\d+$/.test(v)) {
    const n = Number(v);
    return Number.isSafeInteger(n) && n > 0 ? n : null;
  }
  return null;
}

function intField(src: Record<string, unknown>, key: string): number {
  const n = positiveInt(src[key]);
  if (n === null) throw new HttpError(400, `Missing or invalid "${key}".`);
  return n;
}

/**
 * Today's date on the wall clock the group climbs by. This has to be Singapore
 * and not UTC: SGT is UTC+8 all year, so for the eight hours after midnight the
 * UTC date is still yesterday, and "today" would mean two different days
 * depending on what time you got round to logging.
 *
 * The zone is named rather than added as `+8h` so it stays right if Singapore
 * ever moves it again (it has, twice — 1941 and 1982).
 */
const CLIMB_TZ = "Asia/Singapore";

function localToday(): string {
  const parts = new Intl.DateTimeFormat("en-CA", {
    timeZone: CLIMB_TZ,
    year: "numeric",
    month: "2-digit",
    day: "2-digit",
  }).formatToParts(new Date());
  const at = (type: string) => parts.find((part) => part.type === type)!.value;
  return `${at("year")}-${at("month")}-${at("day")}`;
}

/**
 * A calendar date, `YYYY-MM-DD`. The shape check alone would wave through
 * `2026-99-99` and `2026-02-31`, so we round-trip through `Date` — the
 * comparison is what catches the 31st of February, which `Date` would
 * otherwise roll forward to 2 March. Future dates are rejected too: you
 * can't have sent a climb you haven't climbed yet — but "future" is measured
 * against `localToday()`, because a session that runs past midnight is
 * logged on a date UTC has not reached yet.
 *
 * The value has to *be* a string, for the same reason `positiveInt` refuses
 * `[3]`: `String()` would flatten `["2026-09-01"]` into a date that passes.
 */
function dateField(src: Record<string, unknown>, key: string): string {
  const v = src[key];
  if (typeof v !== "string" || !/^\d{4}-\d{2}-\d{2}$/.test(v)) {
    throw new HttpError(400, `"${key}" must look like 2026-09-10.`);
  }
  const d = new Date(`${v}T00:00:00Z`);
  if (Number.isNaN(d.getTime()) || d.toISOString().slice(0, 10) !== v) {
    throw new HttpError(400, `"${key}" isn't a real date.`);
  }
  if (v > localToday()) {
    throw new HttpError(400, "You can't log a send in the future.");
  }
  return v;
}

/**
 * Free text, or nothing. Absent, null and blank all mean nothing, and NULL is
 * how that is stored — an empty string would be a second way to say the same
 * thing.
 *
 * Anything that is not text is a 400 rather than something `String()` turns
 * into a note: `{ note: { why: "flash" } }` used to be stored, verbatim, as
 * the characters `[object Object]`.
 *
 * The 280 cap counts code points, not UTF-16 units, so it cannot slice an
 * emoji in half and leave a lone surrogate in the column. For a note with no
 * astral characters — every note anyone will actually write — that is the same
 * 280 the client's `maxlength` enforces.
 */
const NOTE_MAX = 280;

function noteField(src: Record<string, unknown>): string | null {
  const v = src.note;
  if (v === undefined || v === null) return null;
  if (typeof v !== "string") throw new HttpError(400, `"note" must be text.`);
  const s = [...v.trim()].slice(0, NOTE_MAX).join("");
  return s === "" ? null : s;
}

/**
 * A grade must be on the ladder of the chain that owns this branch. Grades hang
 * off the chain, so logging a BFF grade at a Boulder Planet branch is rejected.
 */
async function assertGradeFitsGym(env: Env, gymId: number, gradeId: number) {
  const ok = await env.DB.prepare(
    `SELECT 1
       FROM gyms g
       JOIN chains c  ON c.id = g.chain_id
       JOIN grades gr ON gr.system_id = c.system_id
      WHERE g.id = ? AND gr.id = ?`,
  )
    .bind(gymId, gradeId)
    .first();
  if (!ok) throw new HttpError(400, "That grade isn't on that gym's ladder.");
}

const SENDS_SQL = `
  SELECT s.id, s.member_id, s.gym_id, s.grade_id, s.sent_on, s.note, s.created_at,
         g.chain_id,
         gr.label AS grade_label, gr.rank AS grade_rank, gr.colour AS grade_colour,
         sy.confidence AS grade_confidence
    FROM sends s
    JOIN gyms g    ON g.id = s.gym_id
    JOIN chains c  ON c.id = g.chain_id
    JOIN systems sy ON sy.id = c.system_id
    JOIN grades gr ON gr.id = s.grade_id
   ORDER BY s.sent_on DESC, s.id DESC`;

async function route(req: Request, env: Env): Promise<Response> {
  const url = new URL(req.url);
  const path = url.pathname;
  const method = req.method;

  if (path === "/api/bootstrap" && method === "GET") {
    const [members, systems, chains, gyms, grades] = await Promise.all([
      env.DB.prepare("SELECT id, name, emoji FROM members ORDER BY name").all(),
      env.DB.prepare("SELECT id, name, confidence, source FROM systems ORDER BY name").all(),
      env.DB.prepare("SELECT id, name, system_id FROM chains ORDER BY name").all(),
      env.DB.prepare(
        `SELECT g.id, g.chain_id, g.branch
           FROM gyms g JOIN chains c ON c.id = g.chain_id
          ORDER BY c.name, g.branch`,
      ).all(),
      env.DB.prepare(
        "SELECT id, system_id, label, rank, ordinal, colour FROM grades ORDER BY system_id, ordinal",
      ).all(),
    ]);
    // A cookie outlives the row it names, so the id in it is a claim, not a
    // fact. Every write path already checks it against `members` and answers
    // 401 so the client goes back to the name picker — but bootstrap is where
    // the client *learns* who it is, and reporting an id that no longer exists
    // told it it was signed in as a member the board has never heard of. The
    // members list is right here, so confirming costs no extra query.
    const claimed = readMemberId(req);
    const me = members.results.some((m) => m.id === claimed) ? claimed : null;

    return json({
      me,
      members: members.results,
      systems: systems.results,
      chains: chains.results,
      gyms: gyms.results,
      grades: grades.results,
    });
  }

  if (path === "/api/session" && method === "POST") {
    const b = await body(req);
    const id = intField(b, "member_id");
    if (!(await memberExists(env, id))) throw new HttpError(404, "Not one of the ten.");
    return json(
      { me: id },
      {
        headers: {
          "set-cookie": `${COOKIE}=${id}; Path=/; HttpOnly; SameSite=Lax; Max-Age=31536000`,
        },
      },
    );
  }

  if (path === "/api/session" && method === "DELETE") {
    return json(
      { me: null },
      { headers: { "set-cookie": `${COOKIE}=; Path=/; HttpOnly; SameSite=Lax; Max-Age=0` } },
    );
  }

  // Everyone reads everything.
  if (path === "/api/sends" && method === "GET") {
    const { results } = await env.DB.prepare(SENDS_SQL).all();
    return json({ sends: results });
  }

  if (path === "/api/sends" && method === "POST") {
    const me = await requireMe(req, env);
    const b = await body(req);
    const gymId = intField(b, "gym_id");
    const gradeId = intField(b, "grade_id");
    await assertGradeFitsGym(env, gymId, gradeId);
    const row = await env.DB.prepare(
      `INSERT INTO sends (member_id, gym_id, grade_id, sent_on, note)
       VALUES (?, ?, ?, ?, ?) RETURNING id`,
    )
      .bind(me, gymId, gradeId, dateField(b, "sent_on"), noteField(b))
      .first<{ id: number }>();
    return json({ id: row!.id }, { status: 201 });
  }

  // The method is part of the match, not something checked after the fact. Doing
  // identity and ownership first meant a method with no handler here — a GET, a
  // PUT — was answered by the *ownership* rule: 403 "that's someone else's send"
  // for a read, on a board where everyone reads everything, and 401 "pick who
  // you are first" for a caller with no cookie. Both told the caller about a
  // route that does not exist, and one of them leaked who owns a send.
  const one = path.match(/^\/api\/sends\/(\d+)$/);
  if (one && (method === "DELETE" || method === "PATCH")) {
    const id = Number(one[1]);
    const me = await requireMe(req, env);
    await assertOwner(env, id, me);

    if (method === "DELETE") {
      await env.DB.prepare("DELETE FROM sends WHERE id = ?").bind(id).run();
      return json({ deleted: id });
    }

    const b = await body(req);
    const gymId = intField(b, "gym_id");
    const gradeId = intField(b, "grade_id");
    await assertGradeFitsGym(env, gymId, gradeId);
    await env.DB.prepare(
      "UPDATE sends SET gym_id = ?, grade_id = ?, sent_on = ?, note = ? WHERE id = ?",
    )
      .bind(gymId, gradeId, dateField(b, "sent_on"), noteField(b), id)
      .run();
    return json({ updated: id });
  }

  throw new HttpError(404, "No such endpoint.");
}

export default {
  async fetch(req: Request, env: Env): Promise<Response> {
    if (!new URL(req.url).pathname.startsWith("/api/")) {
      // `run_worker_first` should mean we never get here, but if the routing
      // config ever changes, hand the request to the assets so a stray path
      // still lands on the app rather than a bare 404.
      return env.ASSETS.fetch(req);
    }
    try {
      return await route(req, env);
    } catch (err) {
      if (err instanceof HttpError) return json({ error: err.message }, { status: err.status });
      console.error(err);
      return json({ error: "Something broke on our side." }, { status: 500 });
    }
  },
} satisfies ExportedHandler<Env>;
